### ISSUE TITLE
Fertig?

### ISSUE THREAD

**Issue by ManamanaTheReal499** [Pos3ydon/business-card-website#5]
Fertig?

_Originally posted by @ManamanaTheReal499 in https://github.com/Pos3ydon/business-card-website/issues/1#issuecomment-1082064701_

**Comment by ManamanaTheReal499** [comment]
du konnsch ba do webseite die items no stackn

**Comment by ManamanaTheReal499** [comment]
musch du wissn

**Comment by Pos3ydon** [comment]
Fürn Moment schun, olleweil brauchts net mehr.
